# Generated by Django 4.0.5 on 2022-06-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='company name')),
                ('ricCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esg_score', models.CharField(max_length=20)),
                ('social', models.CharField(max_length=20)),
                ('governance', models.CharField(max_length=20)),
                ('comparisson_and_rank', models.CharField(max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='api.company')),
            ],
        ),
    ]
